### ISSUE TITLE
Compatibility with 5.x

### ISSUE THREAD

**Issue by spinscale** [elastic/makelogs#18]
There seems to be a compat issue with ES 5.x... I ran `makelogs -c 10000` which created data in an index named `logstash-0` and not time based ones (even though it's not a problem with kibana due to the field stats checking).

**Comment by spalger** [comment]
This is actually how makelogs creates indices now, after merging the fieldstat stuff into Kibana we switched over so that we could benefit from more efficient indexing regardless of how many documents you are indexing. By default it will rollover to a new index every 100.000 documents, but you can change that with the `--indexInterval` or `-i` flags.
